dan-online/autopulse

src/db/models.rs
src/service/mod.rs
src/service/targets/command.rs
src/service/targets/jellyfin.rs
src/service/targets/plex.rs
src/service/webhooks/discord.rs
src/service/webhooks/mod.rs
src/utils/conn.rs
src/utils/settings.rs

Preparation for #4 
Batches events when moved to targets

feat: batch events to targets

---

README.md
src/routes/triggers.rs
src/service/triggers/lidarr.rs
src/service/triggers/mod.rs
src/utils/settings.rs

feat(trigger): lidarr support

---

src/routes/triggers.rs
src/service/targets/jellyfin.rs
src/service/triggers/mod.rs
src/service/triggers/readarr.rs
src/utils/settings.rs

feat(trigger): Readarr

---

Dockerfile.alpine
example/docker-compose-sqlite.yml

I believe SQLite on docker needs perms to write a file in that directory

fix(docker): sqlite related issues

---

README.md
src/service/runner.rs
src/service/targets/emby.rs
src/service/targets/mod.rs
src/service/targets/tdarr.rs
src/utils/settings.rs

feat(target): Tdarr support

---

src/service/targets/plex.rs

fix(plex): provide parent directory instead of absolute file

---

Dockerfile.alpine
src/main.rs

Creates the directory if not found and also sets permissions no matter what

chore(sqlite): permissions

---

README.md
src/routes/triggers.rs
src/service/runner.rs
src/service/targets/fileflows.rs
src/service/targets/mod.rs
src/service/triggers/mod.rs
src/service/triggers/notify.rs
src/utils/settings.rs

- Adds FileFlows as a target
- Adds `excludes` to triggers to ignore targets

feat(target): FileFlows support

---

src/main.rs
src/routes/stats.rs
src/routes/status.rs
src/routes/triggers.rs
src/service/manager.rs
src/service/runner.rs
src/service/webhooks/discord.rs
src/service/webhooks/manager.rs
src/utils/get_timestamp.rs
src/utils/mod.rs
src/utils/settings.rs

feat: batch webhooks

---

Cargo.lock
Cargo.toml
src/main.rs
src/utils/cli.rs
src/utils/mod.rs
src/utils/settings.rs

feat: add settings config argument

---

.github/workflows/continuous-delivery.yml
Cargo.toml
Dockerfile.alpine
README.md
src/build.rs
src/db/conn.rs

- Allows postgres/sqlite support to be enabled/disabled
- Adds delivery for postgres/sqlite specific images
Ref: #30 

feat(database): use features

---

src/service/manager.rs

fix: prevent redundant scans

---

src/service/targets/emby.rs
src/service/targets/mod.rs
src/service/targets/plex.rs
src/utils/default_true.rs
src/utils/mod.rs

Closes #44 
```yaml
targets:
plex:
...
analyze: true
refresh: true
```

feat(plex): add analyze/refresh

---

Cargo.toml
README.md

doc: add contributing section

---

Cargo.lock
Cargo.toml
src/main.rs
src/service/targets/autopulse.rs
src/service/targets/mod.rs
src/service/targets/plex.rs
src/utils/default_true.rs
src/utils/settings.rs

Closes #49 
```yml
targets:
autopulse:
type: autopulse
url: http://localhost:2875
auth:
username: admin
password: password
trigger: "other" # defaults to manual
```
> interestingly if you point this to itself it won't cause an infinite loop
> as the file hasn't "processed", the request to itself will be ignored

feat(targets): autopulse

---

LICENSE

doc(LICENSE): add MIT

---

Cargo.lock
Cargo.toml
src/main.rs
src/utils/logs.rs

fix(logs): local timestamp

---

README.md

doc(README): update arm image tags

---

Dockerfile
Dockerfile.src

fix(docker): update platform argument to use TARGETPLATFORM

---

src/db/models.rs
src/service/manager.rs
src/service/triggers/lidarr.rs
src/service/triggers/readarr.rs
src/service/triggers/sonarr.rs
src/tests/triggers/lidarr.rs
src/tests/triggers/readarr.rs

feat(lidarr/readarr): add request types for rename/delete

---

src/db/models.rs
src/service/targets/fileflows.rs

Update fileflows to reprocess or manually add a file, depending on if it has been processed before

feat(fileflows): enhance file processing with reprocess/manual-add

---

Cargo.lock
Cargo.toml
README.md
src/main.rs
src/routes/triggers.rs
src/service/manager.rs
src/service/runner.rs
src/service/targets/autopulse.rs
src/service/targets/emby.rs
src/service/targets/fileflows.rs
src/service/targets/plex.rs
src/service/targets/tdarr.rs
src/service/triggers/notify.rs
src/settings/target.rs
src/tests/triggers/notify.rs
src/utils/logs.rs
src/utils/mod.rs
src/utils/task_manager.rs

- Added polling backend and option to notify trigger
- Exits on SIGTERM
- Shuts down more gracefully
Ref: #147

feat: `notify` polling backend + better graceful exits

---

Dockerfile

feat(docker): add healthcheck to monitor application status

---

crates/service/src/runner.rs

Reduces looking for old events that weren't found, but finished already

feat(runner): only look for `pending` & `not_found` events

---

crates/service/src/runner.rs
crates/service/src/settings/webhooks/discord.rs
crates/service/src/settings/webhooks/manager.rs

refactor(webhooks): add target for found events

---

.github/workflows/cleanup-pr.yml
.github/workflows/continuous-delivery-docker.yml
README.md

feat(docker): combined arch tags

---

crates/service/src/settings/triggers/notify.rs
crates/service/src/tests/triggers/lidarr.rs
crates/service/src/tests/triggers/notify.rs
crates/service/src/tests/triggers/radarr.rs
crates/service/src/tests/triggers/readarr.rs
crates/service/src/tests/triggers/sonarr.rs
crates/utils/src/lib.rs
flake.lock

Adds filters to `notify` trigger:
```yml
triggers:
notify:
type: "notify"
paths:
- "/media"
filters:
- .*\.mp4
- .*\.mkv
```
Closes #187

feat(notify): add regex filtering

---

crates/service/src/settings/targets/plex.rs

feat(plex): use a recursive strategy for refresh/analyze

---

crates/service/src/settings/app.rs
crates/utils/src/logs.rs
src/main.rs

feat(app): add api_logging option to settings

---

Dockerfile

fix(docker): pass autopulse command directly

---

crates/service/src/settings/opts.rs
crates/utils/src/logs.rs
src/main.rs

Closes #198 
https://8c737bb5.autopulse.pages.dev/autopulse_service/settings/opts/struct.Opts#structfield.log_file_rollover

feat(log): add log file rollover options

---

ui/Dockerfile
ui/package.json
ui/src/lib/components/core/Navbar.svelte
ui/src/routes/+page.svelte
ui/src/routes/login/+page.svelte
ui/src/routes/status/[id]/+page.svelte
ui/uno.config.ts
ui/vite.config.ts
ui/yarn.lock

fix(ui): update icon packages

---

.github/workflows/cleanup-pr.yml
.github/workflows/continuous-delivery-docker.yml
README.md
example/docker-compose-sqlite.yml
example/docker-compose.yml

Also adds artifact attestation

fix(workflow): update Docker workflow to use GitHub registry

---

crates/service/src/settings/targets/emby.rs

Adds X-Emby-Token for backwards compatibility with emby

fix(emby): add extra emby token for compat

---

crates/server/src/routes/triggers.rs
crates/service/src/runner.rs
crates/service/src/settings/triggers/autoscan.rs
crates/service/src/settings/triggers/mod.rs
crates/utils/src/rewrite.rs

feat(triggers): add `autoscan` compatibility trigger

---

ui/biome.json
ui/src/hooks.server.ts
ui/src/lib/components/core/Navbar.svelte
ui/src/routes/+layout.svelte
ui/src/routes/+page.server.ts
ui/src/routes/+page.svelte
ui/src/routes/add/+page.server.ts
ui/src/routes/add/+page.svelte
ui/src/routes/login/+page.server.ts
ui/src/routes/login/+page.svelte
ui/src/routes/status/[id]/+page.server.ts

fix(ui): migration to svelte 5
